title: ""
name: "Perpetua Soiyian Sankale"
description: "Cybersecurity & AI • Ethical Hacker • Cloud Security"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

url: "https://perpetua-k.github.io"
repository: "Perpetua-k/Perpetua.github.io"

plugins:
  - jekyll-include-cache

author:
  avatar: "/images/profile.jpeg"
  
  bio: "AI-driven Cybersecurity | AI MSc Student | Ethical Hacker | Cloud Security | Open to Offensive Security, SOC Analyst, and IT Support Opportunities"
  location: "Nairobi, Kenya"
  email: "sankperpe@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/Perpetua-Sankale"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Perpetua-k"
    - label: "Credly"
      icon: "fas fa-certificate"
      url: "https://www.credly.com/users/perpetua-sankale"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

header:
  nav: main
