title: "Perpetua Sankale"
name: "Perpetua Soiyian Sankale"
description: "Cybersecurity & Web Developer • Ethical Hacker • CTF Player"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
url: "https://perpetua-k.github.io"
repository: "Perpetua-k/perpetua.github.io"

author:
  name: "Perpetua Sankale"
  avatar: "/profile.jpeg"
  bio: "Cybersecurity and Web Developer | Ethical Hacker | CTF Player"
  location: "Nairobi, Kenya"
  email: "sankperpe@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/Perpetua-Sankale"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Perpetua-k"
    - label: "Credly"
      icon: "fas fa-certificate"
      url: "https://www.credly.com/users/perpetua-sankale"

plugins:
  - jekyll-include-cache
  

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      author_profile: true

      nav:
  - title: "Home"
    url: /
    - title: "Resume"
    url: /resume/
  - title: "Projects"
    url: /projects/
  - title: "Labs"
    url: /labs/
  - title: "Contact"
    url: /contact/



      
